baseURL: "https://kayoyin.github.io/blog"
title: Kayo Yin's Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

disqusShortname: "kayoyin"
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kayo Yin's Blog
  description: "Kayo Yin's Blog"
  keywords: [Blog, Portfolio]
  author: Kayo Yin
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  math: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://cdn-icons.flaticon.com/png/512/523/premium/523444.png?token=exp=1654019661~hmac=00bfb586aee600e5093c2afeb3681a9d"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Kayo's Blog"

  # home-info mode
  homeInfoParams:
    Title: "Hi I'm Kayo,"
    Content: I'm an incoming PhD student at UC Berkeley. I write about ML/NLP research, tips for grad school, and personal stories. You can find my older blog posts on [medium](https://medium.com/@kayo.yin).

  socialIcons:
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=Wc8oLVwAAAAJ&hl=en"
    - name: twitter
      url: "https://twitter.com/kayo_yin"
    - name: github
      url: "https://github.com/kayoyin"
    - name: linkedin
      url: "https://linkedin.com/in/kayoyin"
    - name: goodreads
      url: "https://www.goodreads.com/user/show/32481095-kayo-yin"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: 🔍 search
      url: /search/
      weight: 5
    - identifier: homepage
      name: website
      url: https://kayoyin.github.io
      weight: 30
outputs:
  home:
      - HTML
      - RSS
      - JSON 